# Editing Image

In [1]:
import cv2
import numpy as np

# Resize image

In [2]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
cv2.imshow("hi",resize_photo)
cv2.waitKey(0)
cv2.destroyAllWindows()

# use split and merge

In [3]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
resize_photo

array([[[141, 179, 236],
        [145, 202, 241],
        [144, 195, 239],
        ...,
        [213, 241, 228],
        [215, 241, 228],
        [217, 241, 226]],

       [[161, 200, 244],
        [165, 216, 249],
        [160, 218, 237],
        ...,
        [215, 240, 228],
        [215, 240, 229],
        [216, 240, 230]],

       [[206, 240, 234],
        [193, 233, 242],
        [163, 209, 252],
        ...,
        [217, 239, 226],
        [216, 240, 229],
        [214, 240, 230]],

       ...,

       [[ 65,  35,  94],
        [ 68,  39,  96],
        [ 74,  44, 101],
        ...,
        [146, 187, 198],
        [124, 169, 180],
        [135, 181, 192]],

       [[ 71,  48, 103],
        [ 68,  47, 105],
        [ 67,  47, 107],
        ...,
        [148, 191, 196],
        [141, 187, 198],
        [127, 173, 188]],

       [[ 70,  45, 111],
        [ 63,  44, 109],
        [ 62,  46, 108],
        ...,
        [147, 191, 192],
        [141, 184, 192],
        [108, 150, 167]]

In [4]:
B,G,R=cv2.split(resize_photo)

In [5]:
B

array([[141, 145, 144, ..., 213, 215, 217],
       [161, 165, 160, ..., 215, 215, 216],
       [206, 193, 163, ..., 217, 216, 214],
       ...,
       [ 65,  68,  74, ..., 146, 124, 135],
       [ 71,  68,  67, ..., 148, 141, 127],
       [ 70,  63,  62, ..., 147, 141, 108]], dtype=uint8)

In [6]:
G

array([[179, 202, 195, ..., 241, 241, 241],
       [200, 216, 218, ..., 240, 240, 240],
       [240, 233, 209, ..., 239, 240, 240],
       ...,
       [ 35,  39,  44, ..., 187, 169, 181],
       [ 48,  47,  47, ..., 191, 187, 173],
       [ 45,  44,  46, ..., 191, 184, 150]], dtype=uint8)

In [7]:
R

array([[236, 241, 239, ..., 228, 228, 226],
       [244, 249, 237, ..., 228, 229, 230],
       [234, 242, 252, ..., 226, 229, 230],
       ...,
       [ 94,  96, 101, ..., 198, 180, 192],
       [103, 105, 107, ..., 196, 198, 188],
       [111, 109, 108, ..., 192, 192, 167]], dtype=uint8)

In [8]:
# Removing the red color from photo
R.shape

(480, 402)

In [9]:
R[:,:]=0

In [10]:
R

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [11]:
newphoto=cv2.merge([B,G,R])

In [12]:
cv2.imshow("hi",newphoto)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# second way

In [14]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
B,G,R=cv2.split(resize_photo)

In [15]:
R.shape

(480, 402)

In [16]:
R.dtype

dtype('uint8')

In [17]:
zeros=np.zeros((480,402))

In [18]:
zeros=zeros.astype('uint8') # it changes the dtype of zeros variable

In [19]:
zeros

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [20]:
newphoto=cv2.merge([B,G,zeros])

In [21]:
cv2.imshow("hi",newphoto)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
# Third way

In [23]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
resize_photo.shape

(480, 402, 3)

In [24]:
resize_photo[:,:,2]=0

In [25]:
cv2.imshow("hi",resize_photo)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Crop photo

In [26]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
resize_photo.shape

(480, 402, 3)

In [27]:
newphoto=resize_photo[50:300,10:200]

In [28]:
cv2.imshow("hi",newphoto)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Intensity of color

In [29]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
B,G,R=cv2.split(resize_photo)

In [30]:
B

array([[141, 145, 144, ..., 213, 215, 217],
       [161, 165, 160, ..., 215, 215, 216],
       [206, 193, 163, ..., 217, 216, 214],
       ...,
       [ 65,  68,  74, ..., 146, 124, 135],
       [ 71,  68,  67, ..., 148, 141, 127],
       [ 70,  63,  62, ..., 147, 141, 108]], dtype=uint8)

In [31]:
G

array([[179, 202, 195, ..., 241, 241, 241],
       [200, 216, 218, ..., 240, 240, 240],
       [240, 233, 209, ..., 239, 240, 240],
       ...,
       [ 35,  39,  44, ..., 187, 169, 181],
       [ 48,  47,  47, ..., 191, 187, 173],
       [ 45,  44,  46, ..., 191, 184, 150]], dtype=uint8)

In [32]:
R

array([[236, 241, 239, ..., 228, 228, 226],
       [244, 249, 237, ..., 228, 229, 230],
       [234, 242, 252, ..., 226, 229, 230],
       ...,
       [ 94,  96, 101, ..., 198, 180, 192],
       [103, 105, 107, ..., 196, 198, 188],
       [111, 109, 108, ..., 192, 192, 167]], dtype=uint8)

In [33]:
R[:,:] -= 30

In [34]:
newphoto=cv2.merge([B,G,R])

In [35]:
cv2.imshow("hi",newphoto)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Converting image in Blacken white

In [36]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
Gray_image=cv2.cvtColor(resize_photo, cv2.COLOR_BGR2GRAY)

In [37]:
cv2.imshow("hi",Gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Flip image

In [38]:
photo=cv2.imread("photo.jpg")
resize_photo=cv2.resize(photo, (int(photo.shape[1]/4),int(photo.shape[0]/4)))
flip_photo=cv2.flip(resize_photo,1)
cv2.imshow("hi",flip_photo)
cv2.waitKey(0)
cv2.destroyAllWindows()